### ISSUE TITLE
Hi, how do i do LDFLAGS or something

### ISSUE THREAD

**Issue by SolarAquarion** [vifon/vfnmake#1]
I'm trying to do a LD thing for wxgtk

**Comment by SolarAquarion** [comment]
oh it writes a random 11 in Cflags

**Comment by vifon** [comment]
No, there is no support for LDFLAGS. It seems I treated them (while calling them "LFLAGS") like the `-lsomething` flags and they all appear at the end of the linker invocation. You'd need to add a proper LDFLAGFS support. I no longer use this script though.

**Comment by vifon** [comment]
A random 11 in Cflags? Care to elaborate?
